# Generated by Django 2.2.3 on 2020-06-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('image', models.FileField(blank=True, upload_to='media')),
                ('date', models.DateTimeField(auto_now=True)),
                ('dsc', models.TextField(blank=True, max_length=2047)),
            ],
        ),
    ]
